[project]
name = "mcp-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "arxiv>=2.2.0",
    "google-generativeai>=0.8.5",
    "mcp>=1.12.0",
    "nest-asyncio>=1.6.0",
    "python-dotenv>=1.1.1",
]
